/*
https://wiki.archlinux.org/index.php/GNOME
https://wiki.gnome.org/Projects/GnomeShell/CheatSheet
https://wiki.gnome.org/Projects/GnomeShell/Extensions
https://wiki.gnome.org/Projects/GnomeShell/Extensions/Writing
https://blog.fpmurphy.com/2011/11/updating-gnome-shell-extensions-to-work-with-gnome-3-2.html
https://www.bidon.ca/fr/random/2017-02-25-customizing-gnome-shell-3-20
https://unix.stackexchange.com/questions/257163/reduce-title-bar-height-in-gnome-3-gtk-3
https://securitronlinux.com/bejiitaswrath/how-to-make-the-title-bars-in-gnome-shell-much-thinner-than-the-default/
https://www.reddit.com/r/Fedora/comments/80s9gw/how_do_you_get_rid_of_the_huge_title_bar_on/
https://joshtronic.com/2017/07/26/hide-title-bars-in-gnome-shell/
https://github.com/home-sweet-gnome/dash-to-panel
https://github.com/KEIII/gnome-shell-panel-date-format
https://github.com/Daniel-Khodabakhsh/datetime-format
https://github.com/omid/Persian-Calendar-for-Gnome-Shell
https://extensions.gnome.org/extension/1010/archlinux-updates-indicator/
https://developer.gnome.org/shell/stable/
https://gitlab.gnome.org/GNOME/gnome-shell-extensions/tree/master/extensions/window-list
https://gitlab.gnome.org/GNOME/gnome-shell-extensions/tree/master/extensions/user-theme
https://github.com/hedayaty/NetSpeed
*/
