[package]
name = "comshell"
version = "0.1.0"
authors = ["Damoon Saghian <damoonsaghian84@gmail.com>"]
description = "command based user interface"
keywords = ["command-based-ui", "actors"]
repository = "https://github.com/damoonsaghian/Comshell"
license = "Unlicense"
edition = "2018"

[[bin]]
path = "main.rs"

[dependencies]
chrono = ""
chrono-tz = ""
may_actor = "0.2.2"
gtk = { version = "", features = ["v3_22_30"] }
gdk = { version = "", features = ["v3_22_30"] }
sourceview = { version = "", features = ["v3_24"] }
webkit2gtk = { version = "", features = ["v2_16"] }
