#! /bin/bash
set -e

if [[ "$1" == "remove" ]]; then
  pacman --noconfirm -Rns ${@:2}
  # if "/" is "/subvols/0", and "/subvols/1" exists
  arch-chroot /subvols/1 "pacman --noconfirm -Rns ${@:2}"
  # if "/" is "/subvols/1", and "/subvols/0" exists
  arch-chroot /subvols/0 "pacman --noconfirm -Rns ${@:2}"
  exit
fi

if [[ "$1" == "update" || "$1" == "add" ]]; then
  # delete "/subvols/2";
  ## if "/" is "/subvols/0", if "/subvols/1" exists move it to "/subvols/2",
  ##   otherwise create a snapshot of "/subvols/0" in "/subvols/2";
  ## if "/" is "/subvols/1", if "/subvols/0" exists move it to "/subvols/2",
  ##   otherwise create a snapshot of "/subvols/1" in "/subvols/2";
  #btrfs subvolume snapshot /subvols/0 /subvols/1
  #
  #bind_mount "etc home root opt usr/local srv tmp var";
  #
  #arch-chroot /subvols/2 << EOF
  #pacman -Syu --noconfirm
  ## in the case of add requests, install packages;
  ## clear orphaned packages:
  #pacman -Qttdq | pacman -Rns --noconfirm - 2>/dev/null
  ## clear cache:
  #pacman -Sc --noconfirm
  #
  #if [[ "$1" == "add" ]]; then
  #fi
  #EOF
  #
  #mv /subvols/2 /subvols/1
  #arch-chroot /subvols/1 "grub-mkconfig -o /boot/efi/EFI/BOOT/grub.cfg"
  #btrfs subvolume delete /subvols/0
  exit
fi

echo 'usage:
arch add package_name
arch remove package_name
arch update
'
