#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='\[$(tput setab 6)\]\[$(tput setaf 0)\]\w >\[$(tput sgr0)\] '
unset HISTFILE
