[package]
name = "Comshell"
version = "0.0.0"
authors = ["Damoon Saghian <damoonsaghian84@gmail.com>"]
description = "command based user interface"
license = "public domain"

[[bin]]
path = "../main.rs"
name = "comshell"

[dependencies]
futures = "*"
futures-cpupool = "*"
